apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::426030046165:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1H727DFK4Y11W
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::426030046165:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-23T10:26:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1345"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3a5d2858-7833-4cee-bfbc-a530fb93942c
